"""
CyberSentinel v2.0 - Tools Router
Serves the 43-tool arsenal and their sample queries.
"""
from fastapi import APIRouter

router = APIRouter(prefix="/tools", tags=["tools"])

# ═══════════════════════════════════════════════
# TOOL DEFINITIONS - 43 tools across 9 categories
# ═══════════════════════════════════════════════
TOOLS = [
    # ══════════════════════════════════════════════════════
    # 🟢 REAL - These actually execute tools or hit live APIs
    # ══════════════════════════════════════════════════════

    # ── LIVE SCANNERS (execute in Kali sandbox) ──────
    {"id": 1,  "name": "Nmap Scanner",               "cat": "scan",      "color": "#ff3355"},
    {"id": 2,  "name": "SSL/TLS Checker",             "cat": "scan",      "color": "#ff3355"},
    {"id": 3,  "name": "DNS Recon",                   "cat": "scan",      "color": "#ff3355"},
    {"id": 4,  "name": "Nikto Scanner",               "cat": "scan",      "color": "#ff3355"},
    {"id": 5,  "name": "Nuclei Scanner",              "cat": "scan",      "color": "#ff3355"},
    {"id": 6,  "name": "SQLMap Scanner",              "cat": "scan",      "color": "#ff3355"},
    {"id": 7,  "name": "Subfinder",                   "cat": "scan",      "color": "#ff3355"},
    {"id": 8,  "name": "WHOIS Lookup",                "cat": "scan",      "color": "#ff3355"},
    {"id": 9,  "name": "HTTP Headers",                "cat": "scan",      "color": "#ff3355"},
    {"id": 10, "name": "Ping / Traceroute",            "cat": "scan",      "color": "#ff3355"},
    {"id": 11, "name": "OWASP ZAP",                    "cat": "scan",      "color": "#ff3355"},

    # ── LIVE THREAT INTEL (real API calls) ───────────
    {"id": 12, "name": "Shodan API",                  "cat": "intel",     "color": "#00f0ff"},
    {"id": 13, "name": "VirusTotal API",              "cat": "intel",     "color": "#00f0ff"},
    {"id": 14, "name": "AbuseIPDB API",               "cat": "intel",     "color": "#00f0ff"},
    {"id": 15, "name": "OTX AlienVault",              "cat": "intel",     "color": "#00f0ff"},
    {"id": 16, "name": "NVD / CISA KEV",              "cat": "intel",     "color": "#00f0ff"},

    # ── SIEM INTEGRATION (real connections) ───────────
    {"id": 17, "name": "ELK Stack SIEM",              "cat": "siem",      "color": "#00ff88"},
    {"id": 18, "name": "Splunk SIEM",                 "cat": "siem",      "color": "#00ff88"},
    {"id": 19, "name": "Wazuh SIEM",                  "cat": "siem",      "color": "#00ff88"},

    # ══════════════════════════════════════════════════════
    # 🔵 AI-POWERED - AI generates real, usable output
    # ══════════════════════════════════════════════════════

    # ── DETECTION & ANALYSIS (AI expert) ─────────────
    {"id": 20, "name": "Zeek Analyzer",               "cat": "detect",    "color": "#a855f7"},
    {"id": 21, "name": "Threat Detection",            "cat": "detect",    "color": "#a855f7"},
    {"id": 22, "name": "Log Analyzer",                "cat": "detect",    "color": "#a855f7"},
    {"id": 23, "name": "IOC Extractor",               "cat": "detect",    "color": "#a855f7"},
    {"id": 24, "name": "Email Phishing Analyzer",     "cat": "detect",    "color": "#a855f7"},

    # ── THREAT HUNTING & RULE GENERATION ─────────────
    {"id": 25, "name": "SIEM Query Generator",        "cat": "rule",      "color": "#ffd000"},
    {"id": 26, "name": "YARA Rules",                  "cat": "rule",      "color": "#ffd000"},
    {"id": 27, "name": "Sigma Rules",                 "cat": "rule",      "color": "#ffd000"},
    {"id": 28, "name": "Snort/Suricata Rules",        "cat": "rule",      "color": "#ffd000"},

    # ── FRAMEWORKS & COMPLIANCE (AI knowledge) ───────
    {"id": 29, "name": "MITRE ATT&CK",               "cat": "framework", "color": "#ff9500"},
    {"id": 30, "name": "MITRE ATLAS",                 "cat": "framework", "color": "#ff9500"},
    {"id": 31, "name": "Incident Response",           "cat": "framework", "color": "#ff9500"},
    {"id": 32, "name": "Compliance (CIS/NIST/PCI)",   "cat": "framework", "color": "#ff9500"},
    {"id": 33, "name": "Threat Modeling",             "cat": "framework", "color": "#ff9500"},
]

# Sample queries per tool - ONLY for tools that actually exist
TOOL_QUERIES = {
    # ═══ LIVE SCANNERS (real execution in sandbox) ═══
    "Nmap Scanner": [
        "Scan scanme.nmap.org for all open ports",
        "Run service detection scan on 192.168.1.1",
        "Perform OS detection scan on target host",
        "Run stealth SYN scan on top 1000 ports",
        "Scan for SMB vulnerabilities on target network",
        "Run aggressive scan with version detection on scanme.nmap.org",
        "Scan for open RDP and SSH services",
        "Run vulnerability scripts (--script vuln) against target",
        "Detect firewall rules with ACK scan technique",
        "Scan 10.0.0.0/24 for all live hosts and services",
    ],
    "SSL/TLS Checker": [
        "Check SSL certificate for google.com",
        "Scan for weak cipher suites on solventcyber.com",
        "Verify TLS 1.3 support and configuration",
        "Test for BEAST, POODLE, and Heartbleed vulnerabilities",
        "Check certificate chain completeness and validity",
        "Verify HSTS header configuration and preload status",
        "Test for SSL renegotiation vulnerabilities",
        "Detect expired or soon-to-expire certificates",
        "Generate SSL/TLS security audit report",
        "Check certificate transparency logs for our domain",
    ],
    "DNS Recon": [
        "Enumerate all subdomains for solventcyber.com",
        "Check for DNS zone transfer vulnerability on target",
        "Verify SPF, DKIM, and DMARC records for google.com",
        "Check for dangling DNS records (subdomain takeover risk)",
        "Find all DNS record types for target domain",
        "Check for DNSSEC configuration and validation",
        "Detect DNS cache poisoning indicators",
        "DNS recon on example.com - get all records",
        "Check for DNS-over-HTTPS (DoH) resolver configuration",
        "Generate full DNS security audit report",
    ],
    "Nikto Scanner": [
        "Scan http://testphp.vulnweb.com for known web vulnerabilities",
        "Check for dangerous HTTP methods (PUT, DELETE)",
        "Scan for default files and admin panels",
        "Check server headers for information disclosure",
        "Run full Nikto scan against target web app",
        "Test for directory listing and path traversal",
        "Scan for outdated server software versions",
        "Check for common backup and config file exposure",
        "Detect web application firewall (WAF) presence",
        "Scan multiple ports for HTTP services",
    ],
    "Nuclei Scanner": [
        "Run CVE templates against http://testphp.vulnweb.com",
        "Scan for misconfiguration vulnerabilities on target",
        "Test for exposed admin panels and dashboards",
        "Run all critical and high severity templates",
        "Scan for exposed .env and config files",
        "Test for default credentials on web services",
        "Run technology detection templates",
        "Scan for CORS misconfiguration vulnerabilities",
        "Test for SSRF and open redirect vulnerabilities",
        "Nuclei scan on solventcyber.com with all templates",
    ],
    "SQLMap Scanner": [
        "Test URL for SQL injection: http://testphp.vulnweb.com/listproducts.php?cat=1",
        "Run SQL injection scan against login form parameters",
        "Test for blind SQL injection on search endpoint",
        "Enumerate database names via SQL injection",
        "Extract table names from vulnerable parameter",
        "Test for time-based blind SQL injection",
        "Run sqlmap with level 3 risk 2 for thorough testing",
        "Test POST parameters for SQL injection vulnerabilities",
        "Check for stacked queries SQL injection",
        "Run sqlmap OS shell attempt on vulnerable endpoint",
    ],
    "Subfinder": [
        "Find all subdomains for solventcyber.com",
        "Enumerate subdomains for google.com",
        "Discover hidden subdomains for target domain",
        "Run passive subdomain discovery on example.com",
        "Find all subdomains using certificate transparency",
        "Subdomain enumeration for bug bounty target",
        "Discover API subdomains for target organization",
        "Find development/staging subdomains",
        "Enumerate cloud-hosted subdomains",
        "Run subfinder with all passive sources",
    ],
    "WHOIS Lookup": [
        "WHOIS lookup for google.com",
        "Check domain registration details for solventcyber.com",
        "Find registrar and nameservers for target domain",
        "Check domain expiration date",
        "WHOIS lookup for IP 8.8.8.8",
        "Find organization behind a domain",
        "Check domain age and creation date",
        "WHOIS for suspicious domain found in phishing email",
        "Look up domain contact information",
        "Check if domain uses privacy protection",
    ],
    "HTTP Headers": [
        "Check security headers for https://example.com",
        "Scan for missing X-Frame-Options and CSP headers",
        "Check CORS policy on target web application",
        "Verify HSTS implementation on production server",
        "Check for server version disclosure in headers",
        "Scan for missing Referrer-Policy header",
        "Check X-Content-Type-Options configuration",
        "Verify Permissions-Policy header settings",
        "Check for cache-control security headers",
        "Full HTTP header security audit for target",
    ],
    "Ping / Traceroute": [
        "Ping 8.8.8.8 - check if host is alive",
        "Traceroute to scanme.nmap.org - show network path",
        "Check if 192.168.1.1 is reachable",
        "Trace route to solventcyber.com",
        "Ping google.com with 10 packets",
        "Check latency to target server",
        "Traceroute to identify network hops",
        "Verify connectivity to internal server",
        "Ping sweep a subnet",
        "Check for packet loss to target",
    ],
    "Zeek Analyzer": [
        "Capture and analyze network traffic to scanme.nmap.org",
        "Analyze network connections to 8.8.8.8",
        "Capture DNS traffic to 1.1.1.1",
        "Network traffic analysis on solventcyber.com",
        "Capture packets and analyze connections to target host",
        "Analyze network traffic to scanme.nmap.org for HTTP and DNS",
        "Run traffic capture on 45.33.32.156",
        "Capture and analyze SSL/TLS connections to github.com",
        "Analyze network packets to cloudflare.com",
        "Traffic capture and connection analysis on target",
    ],
    "OWASP ZAP": [
        "Run OWASP ZAP scan on http://testphp.vulnweb.com",
        "ZAP web app security scan on target URL",
        "Run OWASP ZAP baseline scan against production site",
        "Check for exposed admin panels and sensitive files with ZAP",
        "Run ZAP against http://testphp.vulnweb.com for OWASP Top 10",
        "OWASP ZAP scan for XSS and injection vulnerabilities",
        "Run web application security test with ZAP",
        "ZAP scan on solventcyber.com",
        "Check for misconfigured security headers with ZAP",
        "Run OWASP ZAP spider and active scan",
    ],

    # ═══ LIVE THREAT INTEL (real API calls) ═══
    "Shodan API": [
        "Shodan lookup for 8.8.8.8",
        "Shodan lookup for 1.1.1.1",
        "Shodan lookup for solventcyber.com",
        "Check what ports are open on 104.26.10.78",
        "Shodan lookup for cloudflare.com",
        "Look up 185.220.101.33 on Shodan",
        "Shodan scan results for 45.33.32.156",
        "Check Shodan for exposed services on scanme.nmap.org",
        "Shodan lookup for github.com",
        "What does Shodan know about 206.189.205.251",
    ],
    "VirusTotal API": [
        "Check IP 185.220.101.33 on VirusTotal",
        "Scan domain evil-c2.xyz on VirusTotal",
        "Check file hash on VirusTotal for malware detection",
        "VirusTotal lookup for suspicious URL",
        "Check if IP is flagged as malicious on VirusTotal",
        "Get VirusTotal report for target domain",
        "Check URL reputation on VirusTotal",
        "Scan suspicious file hash against VirusTotal",
        "VirusTotal analysis for phishing domain",
        "Check multi-engine detection for suspicious hash",
    ],
    "AbuseIPDB API": [
        "Check IP reputation on AbuseIPDB: 185.220.101.33",
        "Report malicious IP to AbuseIPDB",
        "Check abuse confidence score for target IP",
        "Look up IP 91.240.118.172 on AbuseIPDB",
        "Get abuse reports for suspicious IP address",
        "Check if IP has been reported for brute force",
        "AbuseIPDB lookup for C2 server IP",
        "Check IP reputation before whitelisting",
        "Get country and ISP info for malicious IP",
        "Check AbuseIPDB for our firewall blocked IPs",
    ],
    "OTX AlienVault": [
        "Search OTX for threat intel on IP 45.33.32.156",
        "Get OTX pulses for ransomware indicators",
        "Check domain reputation on AlienVault OTX",
        "Search OTX for APT29 indicators",
        "Get latest malware IOCs from OTX",
        "OTX lookup for suspicious file hash",
        "Search OTX for Cobalt Strike C2 indicators",
        "Check if domain is in any OTX threat pulses",
        "Get OTX threat intel for IP range",
        "Search AlienVault for latest phishing IOCs",
    ],
    "NVD / CISA KEV": [
        "Show latest critical CVEs from NVD",
        "Check CISA Known Exploited Vulnerabilities catalog",
        "Search for Apache Log4j CVEs",
        "Get EPSS scores for recent critical vulnerabilities",
        "Show CVEs with CVSS score above 9.0",
        "Check if CVE-2024-1234 is in CISA KEV",
        "Get latest exploited vulnerabilities this week",
        "Search NVD for Microsoft Exchange CVEs",
        "Show all critical CVEs with active exploits",
        "Get EPSS probability for specific CVE",
    ],

    # ═══ SIEM INTEGRATION (real Elasticsearch) ═══
    "ELK Stack SIEM": [
        "Check ELK cluster health and status",
        "Query ELK for failed login attempts in last 24 hours",
        "Search ELK for lateral movement indicators (Event 4648, 4624 Type 3)",
        "Pull high-severity alerts from Elasticsearch",
        "Query ELK for PowerShell execution events",
        "Search Elasticsearch for DNS queries to suspicious domains",
        "Query ELK for process creation events matching mimikatz",
        "Pull all security alerts from ELK SIEM",
        "Check Elasticsearch for brute force patterns",
        "Search ELK for credential dumping indicators",
    ],
    "Splunk SIEM": [
        "Check Splunk connection health and status",
        "Query Splunk for failed login attempts in last 24 hours",
        "Search Splunk for lateral movement - index=wineventlog EventCode=4648",
        "Run SPL query for brute force detection on Splunk",
        "Search Splunk for PowerShell execution events",
        "Pull Splunk alerts for high-severity incidents",
        "Query Splunk for DNS exfiltration indicators",
        "Run Splunk search for privilege escalation events",
        "Search Splunk for C2 beaconing activity",
        "Generate Splunk dashboard for SOC monitoring",
    ],
    "Wazuh SIEM": [
        "Check Wazuh manager health and agent status",
        "Query Wazuh for failed login alerts in last 24 hours",
        "Search Wazuh for file integrity monitoring (FIM) changes",
        "Pull Wazuh vulnerability detection results for all agents",
        "Query Wazuh for rootkit detection alerts",
        "Search Wazuh for active response triggers",
        "Check Wazuh agent inventory and compliance status",
        "Pull Wazuh SCA (Security Configuration Assessment) results",
        "Query Wazuh for brute force attack alerts (rule 5712)",
        "Search Wazuh for MITRE ATT&CK mapped alerts",
    ],

    # ═══ AI-POWERED (generates real output) ═══
    "Threat Detection": [
        "Detect lateral movement patterns in Windows Event logs (4624 Type 3, 4648)",
        "Identify C2 beaconing activity with interval analysis and jitter detection",
        "Hunt for PowerShell-based fileless malware - script block logging, AMSI bypass",
        "Detect pass-the-hash attacks - Event 4624 with NTLM, no Kerberos",
        "Identify suspicious DNS tunneling - long subdomains, high query volume, TXT records",
        "Detect scheduled task persistence - Event 4698, schtasks.exe, at.exe",
        "Hunt for credential dumping - LSASS access (Event 4663, 10), Mimikatz signatures",
        "Detect living-off-the-land (LOLBin) attacks - certutil, mshta, regsvr32, rundll32",
        "Find DLL sideloading and hijacking patterns",
        "Detect data staging before exfiltration - compression, archive, staging directories",
        "Hunt for Kerberoasting - Event 4769 with RC4 encryption (0x17)",
        "Detect DCSync attacks - Directory Replication Service requests from non-DC",
        "Hunt for Golden Ticket - Event 4769 with forged TGT",
        "Detect WMI persistence - Event 5861, WMI consumer/filter pairs",
        "Hunt for process injection - CreateRemoteThread, NtQueueApcThread, hollow process",
    ],
    "Log Analyzer": [
        "Analyze Windows Event logs for failed login patterns (4625) - extract IPs, users, frequency",
        "Parse syslog data for firewall deny events - top blocked IPs and ports",
        "Find brute force patterns in authentication logs - threshold analysis",
        "Identify off-hours access in Active Directory logs - baseline vs anomaly",
        "Analyze Apache access logs for SQL injection attempts (SELECT, UNION, OR 1=1)",
        "Parse CEF format logs from Palo Alto firewall - top threats and actions",
        "Find privilege escalation events in sudo/su logs",
        "Detect service account abuse in audit logs - non-standard usage patterns",
        "Analyze VPN connection logs for anomalous geolocations (impossible travel)",
        "Parse JSON format security logs and summarize findings",
        "Analyze Windows Security Event log - summarize 4624/4625/4648/4672 patterns",
        "Correlate multiple log sources - firewall + auth + endpoint for incident timeline",
        "Parse and analyze AWS CloudTrail logs for suspicious API calls",
        "Analyze Linux auth.log for SSH brute force and successful compromises",
        "Parse DNS query logs for DGA (Domain Generation Algorithm) detection",
    ],
    "IOC Extractor": [
        "Extract all IPs, domains, URLs, and hashes from this threat report",
        "Parse email headers and extract sender IP, domain, and authentication results",
        "Extract IOCs from malware analysis report - file hashes, C2 domains, mutexes",
        "Pull all indicators from this incident writeup - create structured IOC list",
        "Extract URLs and file hashes from phishing email body",
        "Parse threat advisory and create STIX 2.1 formatted IOC bundle",
        "Extract C2 indicators from network capture - beaconing IPs and domains",
        "Parse and deduplicate IOCs from multiple sources into single list",
        "Extract all observables from PDF threat report",
        "Create OpenIOC formatted indicators from incident artifacts",
    ],
    "Email Phishing Analyzer": [
        "Analyze this email for phishing indicators - headers, links, sender reputation",
        "Check email headers for SPF/DKIM/DMARC alignment failures",
        "Extract and analyze all URLs from suspicious email - check against threat intel",
        "Check sender domain age, registration, and reputation",
        "Identify social engineering techniques used in this email",
        "Analyze attachment type - check for macros, embedded scripts, double extensions",
        "Check for homograph attacks in email links (IDN spoofing)",
        "Verify email authentication chain - SPF, DKIM, DMARC, ARC",
        "Generate phishing incident report with severity and recommended actions",
        "Score email threat level (1-10) and recommend block/allow/quarantine",
    ],
    "SIEM Query Generator": [
        "Generate Splunk SPL query for brute force detection (>5 failures in 5 min)",
        "Create Elastic KQL query for lateral movement (Event 4648 + Type 3 logon)",
        "Build KQL query for Azure Sentinel - suspicious PowerShell execution",
        "Generate QRadar AQL for privilege escalation detection",
        "Create Splunk SPL for C2 beaconing detection (regular interval analysis)",
        "Build Elastic query for DNS tunneling detection (long subdomain queries)",
        "Generate SIEM correlation rule for ransomware kill chain",
        "Create Splunk query for detecting scheduled task persistence",
        "Build Elastic SIEM query for process injection detection",
        "Generate Splunk dashboard XML for SOC monitoring - top 10 panels",
        "Create Splunk SPL for impossible travel detection (geo-IP analysis)",
        "Build KQL for Microsoft Sentinel - Azure AD risky sign-ins",
        "Generate CrowdStrike LogScale query for endpoint detection",
        "Create Chronicle SIEM query using UDM for threat detection",
        "Generate multi-SIEM query comparison - same detection in Splunk vs Elastic vs Sentinel",
    ],
    "YARA Rules": [
        "Create YARA rule for detecting Cobalt Strike beacon in memory",
        "Generate YARA rule for ransomware encryption patterns (entropy + extension changes)",
        "Write YARA rule matching packed PE executables (UPX, Themida, VMProtect)",
        "Create YARA rule for detecting webshells (PHP, ASP, JSP)",
        "Generate YARA rule for PowerShell downloader patterns",
        "Write YARA rule for Emotet malware family indicators",
        "Create YARA rule detecting base64 encoded payloads in documents",
        "Generate YARA rule for document macro malware (VBA, XLM)",
        "Write YARA rule for cryptominer detection (XMRig, Monero patterns)",
        "Create YARA rule matching Mimikatz tool signatures",
        "Generate YARA rule for detecting .NET malware (assemblies, obfuscation)",
        "Write YARA rule for RAT detection (Remote Access Trojans)",
        "Create YARA rule for malicious JavaScript (obfuscated, eval, document.write)",
        "Generate YARA rule for detecting shellcode in files",
        "Write YARA rule for Sliver C2 framework detection",
    ],
    "Sigma Rules": [
        "Create Sigma rule for detecting mimikatz execution (process name, command line)",
        "Generate Sigma rule for suspicious service installation (Event 7045)",
        "Write Sigma rule for credential dumping via LSASS access (Event 10)",
        "Create Sigma rule for lateral movement via WMI (Event 5861, wmic.exe)",
        "Generate Sigma rule for PowerShell download cradle (IEX, DownloadString)",
        "Write Sigma rule for scheduled task persistence (Event 4698, schtasks.exe)",
        "Create Sigma rule for DCSync attack detection (Directory Replication Service)",
        "Generate Sigma rule for Kerberoasting activity (Event 4769, 0x17)",
        "Write Sigma rule for suspicious DNS queries (DGA, tunneling, high entropy)",
        "Create Sigma rule for data exfiltration indicators (archive + upload)",
        "Generate Sigma rule for process injection techniques (CreateRemoteThread)",
        "Write Sigma rule for LOLBin abuse - certutil, mshta, regsvr32, rundll32",
        "Create Sigma rule for pass-the-hash detection (Event 4624, NTLM logon)",
        "Generate Sigma rule for UAC bypass techniques",
        "Write Sigma rule for suspicious registry modifications (autostart locations)",
    ],
    "Snort/Suricata Rules": [
        "Create Snort rule for detecting C2 traffic patterns (beaconing interval)",
        "Generate Suricata rule for SQL injection in HTTP requests",
        "Write IDS rule for detecting port scanning (SYN flood, connect scan)",
        "Create Snort rule for DNS tunneling detection (TXT queries, long subdomains)",
        "Generate Suricata rule for TLS certificate anomalies (self-signed, expired)",
        "Write rule for detecting SSH brute force (multiple auth failures)",
        "Create IDS rule for lateral movement via SMB (EternalBlue, PsExec)",
        "Generate Snort rule for malware download detection (suspicious User-Agent)",
        "Write Suricata rule for detecting beaconing (regular HTTP/HTTPS intervals)",
        "Create rule for detecting ICMP tunneling (oversized ICMP, regular patterns)",
        "Generate Suricata rule for detecting DGA domains in DNS",
        "Write Snort rule for detecting web shell access patterns",
        "Create rule for detecting Cobalt Strike Malleable C2 profiles",
        "Generate Suricata rule for detecting data exfiltration over DNS",
        "Write IDS rule for detecting ARP spoofing / MITM attacks",
    ],
    "Incident Response": [
        "Generate incident response playbook for ransomware - containment, eradication, recovery",
        "Create IR checklist for compromised credentials (password spray, credential stuffing)",
        "Build containment strategy for active breach with lateral movement detected",
        "Generate forensic evidence collection checklist - memory, disk, network, logs",
        "Create communication plan for security incident - internal + external stakeholders",
        "Build forensic timeline from incident artifacts (Windows Event Logs, network logs)",
        "Generate post-incident review template (lessons learned, root cause, improvements)",
        "Create IR playbook for Business Email Compromise (BEC) attack",
        "Create IR playbook for phishing attack - triage, scope, remediation",
        "Create IR playbook for supply chain compromise",
        "Build evidence preservation chain of custody document",
        "Generate executive incident summary report for leadership",
        "NIST SP 800-61 - Incident Response lifecycle phases explained",
        "SANS Incident Response 6-step process - Preparation through Lessons Learned",
        "Create IR playbook for insider threat detection and response",
        "Create IR playbook for DDoS attack mitigation",
        "Create IR playbook for data exfiltration - detection, containment, notification",
        "Create IR playbook for cloud account compromise (AWS/Azure/GCP)",
        "Generate incident severity classification matrix (P1-P4)",
        "Create IR communication templates - legal, PR, customer notification",
    ],
    "Compliance (CIS/NIST/PCI)": [
        "CIS Controls v8 - Complete overview of all 18 controls and 153 safeguards",
        "CIS Controls Implementation Group 1 (IG1) - All 56 essential safeguards",
        "CIS Controls Implementation Group 2 (IG2) - Additional safeguards beyond IG1",
        "CIS Controls Implementation Group 3 (IG3) - Full enterprise safeguards",
        "CIS Control 1: Inventory and Control of Enterprise Assets - all safeguards",
        "CIS Control 4: Secure Configuration - all safeguards",
        "CIS Control 6: Access Control Management - all safeguards",
        "CIS Control 8: Audit Log Management - all safeguards",
        "CIS Control 13: Network Monitoring and Defense - all safeguards",
        "Generate CIS Benchmark audit checklist for Windows Server 2022",
        "Generate CIS Benchmark audit checklist for Ubuntu Linux",
        "NIST 800-53 Rev 5 - Complete overview of all control families",
        "NIST Cybersecurity Framework (CSF) 2.0 - All 6 functions explained",
        "Map our security controls to NIST 800-53 control families",
        "NIST 800-171 - CUI protection requirements for government contractors",
        "Assess NIST CSF maturity level for our security program",
        "PCI DSS v4.0 - All 12 requirements explained",
        "Generate PCI-DSS v4.0 compliance gap analysis",
        "HIPAA Security Rule - All technical safeguard requirements",
        "SOC 2 Type II - Trust Services Criteria explained",
        "Map security controls to ISO 27001:2022 Annex A controls",
        "FedRAMP authorization requirements and control baseline",
        "CMMC 2.0 - All 3 levels and practice requirements",
        "Generate compliance report template for audit preparation",
    ],
    "Threat Modeling": [
        "Create STRIDE threat model for web application - all 6 categories",
        "STRIDE explained - Spoofing, Tampering, Repudiation, Info Disclosure, DoS, EoP",
        "Generate attack tree for authentication bypass scenarios",
        "Perform DREAD risk assessment for API endpoints",
        "Create data flow diagram (DFD) for threat analysis",
        "PASTA threat modeling - 7-stage process for risk-centric analysis",
        "Create threat model for microservices architecture",
        "Create threat model for cloud migration (AWS/Azure/GCP)",
        "OWASP Top 10 2021 - All 10 risks with detection and mitigation",
        "OWASP API Security Top 10 - All API-specific risks",
        "Create threat model for IoT deployment",
        "Create attack surface analysis for our infrastructure",
        "Identify threats for Zero Trust architecture implementation",
        "Create threat model for mobile application (Android/iOS)",
        "Generate threat model for CI/CD pipeline security",
    ],
    "MITRE ATT&CK": [
        "MITRE ATT&CK v14 - Complete overview of all tactics, techniques, and sub-techniques",
        "TA0043 Reconnaissance - List all techniques for target information gathering",
        "TA0042 Resource Development - Explain infrastructure, accounts, capability acquisition",
        "TA0001 Initial Access - All techniques: phishing, exploits, supply chain, trusted relationships",
        "TA0002 Execution - All techniques: PowerShell, WMI, scripting, scheduled tasks",
        "TA0003 Persistence - All techniques: registry run keys, scheduled tasks, DLL hijacking, boot scripts, account creation",
        "TA0004 Privilege Escalation - All techniques: exploitation, token manipulation, UAC bypass, valid accounts",
        "TA0005 Defense Evasion - All techniques: obfuscation, indicator removal, masquerading, rootkits, process injection",
        "TA0006 Credential Access - All techniques: LSASS dump, Kerberoasting, brute force, DCSync, credential harvesting",
        "TA0007 Discovery - All techniques: account, network, system, permission group, remote system discovery",
        "TA0008 Lateral Movement - All techniques: RDP, SMB, PsExec, WMI, SSH, pass-the-hash, pass-the-ticket",
        "TA0009 Collection - All techniques: screen capture, keylogging, email collection, clipboard, data staging",
        "TA0011 Command and Control - All techniques: web protocols, DNS, encrypted channels, proxy, tunneling",
        "TA0010 Exfiltration - All techniques: C2 channel, web services, physical media, scheduled transfer",
        "TA0040 Impact - All techniques: data destruction, encryption, defacement, resource hijacking, DoS",
        "T1059 Command and Scripting Interpreter - .001 PowerShell, .003 Windows Cmd, .005 VB, .007 JavaScript",
        "T1003 OS Credential Dumping - .001 LSASS, .002 SAM, .003 NTDS, .004 LSA Secrets, .006 DCSync",
        "T1021 Remote Services - .001 RDP, .002 SMB, .003 DCOM, .004 SSH, .005 VNC, .006 WinRM",
        "T1078 Valid Accounts - .001 Default, .002 Domain, .003 Local, .004 Cloud - detection and mitigation",
        "T1053 Scheduled Task/Job - .002 At, .003 Cron, .005 Scheduled Task - detection and hunting",
        "T1547 Boot or Logon Autostart Execution - .001 Registry Run Keys, .004 Winlogon, .009 Shortcuts",
        "T1055 Process Injection - .001 DLL, .003 Thread Hijacking, .012 Process Hollowing - detection",
        "T1071 Application Layer Protocol - .001 Web, .002 File Transfer, .004 DNS for C2 detection",
        "T1027 Obfuscated Files - .001 Binary Padding, .003 Steganography, .010 Command Obfuscation",
        "T1110 Brute Force - .001 Guessing, .002 Cracking, .003 Spraying, .004 Credential Stuffing",
        "Map APT29 (Cozy Bear) TTPs to MITRE ATT&CK - all known techniques and campaigns",
        "Map APT28 (Fancy Bear) TTPs - initial access through exfiltration",
        "Map Lazarus Group TTPs - all known techniques and campaigns",
        "Map FIN7/Carbanak TTPs - financial sector attack patterns",
        "Map Volt Typhoon TTPs - living-off-the-land techniques",
        "Generate ATT&CK Navigator heatmap of our detection coverage",
        "Identify detection gaps across all 14 tactics",
        "Map our Sigma rules to ATT&CK techniques for coverage analysis",
        "Generate threat hunting playbook based on ATT&CK top 20 techniques",
        "Create ATT&CK-based detection engineering priority matrix",
        "Map MITRE ATT&CK to NIST 800-53 controls",
        "Map MITRE ATT&CK to CIS Controls v8",
        "Explain ATT&CK for ICS (Industrial Control Systems)",
        "Explain ATT&CK for Mobile - Android and iOS techniques",
        "What is MITRE D3FEND and how does it complement ATT&CK?",
        "Compare ATT&CK Enterprise vs Cloud vs ICS matrices",
        "Explain the ATT&CK kill chain for a ransomware attack end-to-end",
    ],
    "MITRE ATLAS": [
        "MITRE ATLAS v4 - Complete overview of all AI/ML adversary tactics and techniques",
        "List ALL ATLAS tactics: Reconnaissance through Impact for ML systems",
        "How does MITRE ATLAS differ from ATT&CK? When to use each?",
        "AML.TA0001 ML Attack Staging - Reconnaissance and resource development for AI attacks",
        "AML.TA0002 ML Model Access - Techniques for gaining access to ML models (API, physical, insider)",
        "AML.TA0003 ML Attack Execution - Evasion, poisoning, and functional extraction attacks",
        "AML.TA0004 ML Attack Impact - Model denial of service, output integrity, and harm",
        "AML.T0000 ML Supply Chain Compromise - Attacking training data, libraries, and pre-trained models",
        "AML.T0010 ML Supply Chain - Poisoned models, backdoored libraries, compromised datasets",
        "AML.T0015 Evade ML Model - Evasion attacks against classifiers and detectors",
        "AML.T0018 Backdoor ML Model - Trojan attacks on neural networks",
        "AML.T0019 Publish Poisoned Dataset - Attacking through training data manipulation",
        "AML.T0020 Poison Training Data - Data poisoning techniques and detection",
        "AML.T0024 Exfiltration via ML Inference API - Model extraction and data leakage",
        "AML.T0040 ML Model Inference API Access - Query-based attacks on deployed models",
        "AML.T0042 Verify Attack - Validating adversarial examples work in production",
        "AML.T0043 Craft Adversarial Data - Creating inputs that fool ML models",
        "AML.T0044 Full ML Model Access - White-box attacks with complete model knowledge",
        "AML.T0047 ML-Enabled Product/Service - Attacking consumer-facing AI applications",
        "ATLAS techniques for prompt injection attacks on LLMs (ChatGPT, Claude, etc.)",
        "ATLAS techniques for jailbreaking and guardrail bypass in LLMs",
        "ATLAS coverage of training data extraction from language models",
        "How ATLAS maps data poisoning attacks against fine-tuned LLMs",
        "ATLAS techniques for AI supply chain attacks (Hugging Face, PyPI, model zoos)",
        "ATLAS Case Study: Microsoft Tay chatbot manipulation",
        "ATLAS Case Study: Adversarial attacks on autonomous vehicles",
        "ATLAS Case Study: GPT model extraction attacks",
        "ATLAS Case Study: Poisoning attacks on federated learning",
        "ATLAS Case Study: Evasion attacks on malware classifiers",
        "ALL ATLAS mitigations - complete list of AI/ML defenses",
        "ATLAS mitigations for model poisoning and backdoor attacks",
        "ATLAS mitigations for adversarial evasion attacks",
        "ATLAS mitigations for model extraction and theft",
        "ATLAS mitigations for prompt injection in LLM applications",
        "Generate AI/ML security assessment using ATLAS framework",
        "Generate red team plan for LLM application using ATLAS",
        "Map our AI defenses to ATLAS mitigation strategies",
        "Assess supply chain risks for our ML pipeline per ATLAS",
        "Create ATLAS-based AI security maturity assessment",
    ],
}


@router.get("/")
async def list_tools():
    """Return all 28 tools with their categories."""
    return {"tools": TOOLS, "total": len(TOOLS)}


@router.get("/queries")
async def get_tool_queries_by_param(name: str = ""):
    """Return sample queries for a tool (query param version)."""
    queries = TOOL_QUERIES.get(name, [])
    return {"tool": name, "queries": queries}


@router.get("/{tool_name:path}/queries")
async def get_tool_queries(tool_name: str):
    """Return sample queries for a specific tool."""
    queries = TOOL_QUERIES.get(tool_name, [])
    return {"tool": tool_name, "queries": queries}


@router.get("/categories")
async def list_categories():
    """Return tool categories with counts."""
    cats = {}
    for t in TOOLS:
        cat = t["cat"]
        cats[cat] = cats.get(cat, 0) + 1
    return {"categories": cats}
